WIP: Update all `build.zig`s to the latest Zig nightly
zig-gamedev/zig-gamedev pull request #457
Opened 2024-01-07 07:24 UTC by mochalins

Currently running into a few `XXX.h` missing `cInclude` issues (seems to be okay when running each lib's individual `build.zig` (even `zig build test`), but problematic when building from root `build.zig`). Still WIP, but more eyes would be appreciated.

2024-01-07 19:40 UTC, btipling commented
@mochalins I also took a stab at this unknowing you had a PR, mine builds but I don't know if it's the best approach, just leaving a link here if you find it helpful: https://github.com/michal-z/zig-gamedev/compare/main...btipling:zig-gamedev:target_changes?expand=1

2024-01-10 08:30 UTC, mochalins commented
@hazeycode Root `build.zig` and tests passing now, seems all updates to latest Zig master are good. Tested using version `0.12.0-dev.2139+e025ad7b4`. Rebased on latest `unstable` branch for cleaner history. Would appreciate a PR/comments!

2024-01-10 11:53 UTC, hazeycode commented
Looks good! Thanks for working on this.

Please could you update the minimum zig version in build.zig and the version specified in README.md to the specific version you have tested with?

2024-01-11 00:12 UTC, mochalins commented
> Looks good! Thanks for working on this.
> 
> Please could you update the minimum zig version in build.zig and the version specified in README.md to the specific version you have tested with?

Rebased on latest `unstable` and updated versions! Please let me know if there's anything else to be done, thanks.

2024-01-11 09:07 UTC, hazeycode requested changes

2024-01-11 09:07 UTC, hazeycode commented on libs/zsdl/build.zig
> +                exe.root_module.addRPath(.{ .path = "@executable_path/Frameworks" });
```suggestion
               exe.root_module.addRPathSpecial("@executable_path/Frameworks");
```
This fixes a compile error on macOS

2024-01-11 09:14 UTC, merged

2024-01-11 09:15 UTC, hazeycode commented
Thanks!

2024-01-13 18:06 UTC, btipling commented
@mochalins sorry I missed your comment, fwiw I was building on Windows 11