zgui: add ImGui default colors style API
zig-gamedev/zig-gamedev pull request #704
Opened 2024-09-11 22:26 UTC by okvik

This adds the `ImGui::StyleColors{Dark,Light,Classic}` API to the `zgui.Style` struct.

Compressing these functions to a single function with a style variant argument, and naming it to `Style.setDefaultColors` is a choice that's up for debate. It seems kinda nice to me, but I'm open to changing it to whatever if people disagree.

2024-09-13 20:01 UTC, hazeycode requested changes
This is nitpicky but I think we should **not** call these "default colours" and rather name `DefaultColours` as `StyleColoursBuiltin` and instead of `setDefaultColors` we should have `styleColorsDark`, `styleColorsLight` and `styleColorsClassic` as well as `styleColorsBuiltin`. This would be closer to the underlying API and offer the least surprises for users.

2024-09-15 14:23 UTC, okvik commented
Alright, will do. Though I don't think I understand from what you wrote what exactly you'd like the API to be.

Keeping up with the upstream API there's two options:

1. Style.styleColorsDark() or Light() or Classic()
2. Style.styleColors(.dark) or .light or .classic

2024-09-15 15:29 UTC, hazeycode commented
I had misread things and my previous message was confused and confusing. Sorry about that.

I think the core API here should be:
`styleColorsDark(&style)`, `styleColorsLight(&style)`, `styleColoursClassic(&style)` defined in the top level namespace.

In addition, as "member functions" of `Style` we can have:
`style.setColorsDark()`, `style.setColorsLight()`, `style.setColoursClassic()`
which can be defined as equal to the top-level definitions.

We do [something similar in zsdl.](https://github.com/zig-gamedev/zig-gamedev/blob/fbf96714ab6876646a29824a3b4ba79e34906a6d/libs/zsdl/src/sdl2.zig#L200). And I think this a nice way to offer both plain C-style bindings and an embellished "zigified" API that the user can choose at their discretion.

And I think there is value in embellishing the API further with an enum variant as you have done in your original changeset. `style.setColorsBuiltin(.light)`.

2024-09-15 16:02 UTC, okvik commented
Done. Would you like me to squash the changes or leave the history as-is?

2024-09-15 16:07 UTC, hazeycode commented
Thank you ❤️
And that's ok, I can squash on merge.

2024-09-15 16:20 UTC, hazeycode approved these changes

2024-09-15 16:22 UTC, merged